import type { Metadata } from "next";
import "./globals.css";
import { Merriweather, Noto_Serif } from "next/font/google";
import { cn } from "@/lib/utils";

const notoSerifHeading = Noto_Serif({subsets:['latin'],variable:'--font-heading'});

const merriweather = Merriweather({subsets:['latin'],variable:'--font-serif'});

export const metadata: Metadata = {
  title: "serverpulse",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-serif", merriweather.variable, notoSerifHeading.variable)}>
      <body>{children}</body>
    </html>
  );
}
